//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsFactura
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private string EmpresaField;
        
        private string NroFacturaField;
        
        private string CIField;
        
        private string NombreCompletoField;
        
        private string PeriodoField;
        
        private decimal MontoField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NroFactura
        {
            get
            {
                return this.NroFacturaField;
            }
            set
            {
                this.NroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Periodo
        {
            get
            {
                return this.PeriodoField;
            }
            set
            {
                this.PeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rsFactura.wsNotificadorPagosSoap")]
    public interface wsNotificadorPagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        rsFactura.ConsultarDeudasResponse ConsultarDeudas(rsFactura.ConsultarDeudasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarDeudas", ReplyAction="*")]
        System.Threading.Tasks.Task<rsFactura.ConsultarDeudasResponse> ConsultarDeudasAsync(rsFactura.ConsultarDeudasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento facturas del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        rsFactura.PagarResponse Pagar(rsFactura.PagarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pagar", ReplyAction="*")]
        System.Threading.Tasks.Task<rsFactura.PagarResponse> PagarAsync(rsFactura.PagarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudas", Namespace="http://tempuri.org/", Order=0)]
        public rsFactura.ConsultarDeudasRequestBody Body;
        
        public ConsultarDeudasRequest()
        {
        }
        
        public ConsultarDeudasRequest(rsFactura.ConsultarDeudasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ConsultarDeudasRequestBody()
        {
        }
        
        public ConsultarDeudasRequestBody(string ci)
        {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarDeudasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarDeudasResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsFactura.ConsultarDeudasResponseBody Body;
        
        public ConsultarDeudasResponse()
        {
        }
        
        public ConsultarDeudasResponse(rsFactura.ConsultarDeudasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarDeudasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsFactura.Factura[] ConsultarDeudasResult;
        
        public ConsultarDeudasResponseBody()
        {
        }
        
        public ConsultarDeudasResponseBody(rsFactura.Factura[] ConsultarDeudasResult)
        {
            this.ConsultarDeudasResult = ConsultarDeudasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pagar", Namespace="http://tempuri.org/", Order=0)]
        public rsFactura.PagarRequestBody Body;
        
        public PagarRequest()
        {
        }
        
        public PagarRequest(rsFactura.PagarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsFactura.Factura[] facturas;
        
        public PagarRequestBody()
        {
        }
        
        public PagarRequestBody(rsFactura.Factura[] facturas)
        {
            this.facturas = facturas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsFactura.PagarResponseBody Body;
        
        public PagarResponse()
        {
        }
        
        public PagarResponse(rsFactura.PagarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PagarResult;
        
        public PagarResponseBody()
        {
        }
        
        public PagarResponseBody(string PagarResult)
        {
            this.PagarResult = PagarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsNotificadorPagosSoapChannel : rsFactura.wsNotificadorPagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsNotificadorPagosSoapClient : System.ServiceModel.ClientBase<rsFactura.wsNotificadorPagosSoap>, rsFactura.wsNotificadorPagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsNotificadorPagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsNotificadorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsNotificadorPagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsNotificadorPagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsNotificadorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsNotificadorPagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsNotificadorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsNotificadorPagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsFactura.ConsultarDeudasResponse rsFactura.wsNotificadorPagosSoap.ConsultarDeudas(rsFactura.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudas(request);
        }
        
        public rsFactura.Factura[] ConsultarDeudas(string ci)
        {
            rsFactura.ConsultarDeudasRequest inValue = new rsFactura.ConsultarDeudasRequest();
            inValue.Body = new rsFactura.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            rsFactura.ConsultarDeudasResponse retVal = ((rsFactura.wsNotificadorPagosSoap)(this)).ConsultarDeudas(inValue);
            return retVal.Body.ConsultarDeudasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsFactura.ConsultarDeudasResponse> rsFactura.wsNotificadorPagosSoap.ConsultarDeudasAsync(rsFactura.ConsultarDeudasRequest request)
        {
            return base.Channel.ConsultarDeudasAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsFactura.ConsultarDeudasResponse> ConsultarDeudasAsync(string ci)
        {
            rsFactura.ConsultarDeudasRequest inValue = new rsFactura.ConsultarDeudasRequest();
            inValue.Body = new rsFactura.ConsultarDeudasRequestBody();
            inValue.Body.ci = ci;
            return ((rsFactura.wsNotificadorPagosSoap)(this)).ConsultarDeudasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsFactura.PagarResponse rsFactura.wsNotificadorPagosSoap.Pagar(rsFactura.PagarRequest request)
        {
            return base.Channel.Pagar(request);
        }
        
        public string Pagar(rsFactura.Factura[] facturas)
        {
            rsFactura.PagarRequest inValue = new rsFactura.PagarRequest();
            inValue.Body = new rsFactura.PagarRequestBody();
            inValue.Body.facturas = facturas;
            rsFactura.PagarResponse retVal = ((rsFactura.wsNotificadorPagosSoap)(this)).Pagar(inValue);
            return retVal.Body.PagarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsFactura.PagarResponse> rsFactura.wsNotificadorPagosSoap.PagarAsync(rsFactura.PagarRequest request)
        {
            return base.Channel.PagarAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsFactura.PagarResponse> PagarAsync(rsFactura.Factura[] facturas)
        {
            rsFactura.PagarRequest inValue = new rsFactura.PagarRequest();
            inValue.Body = new rsFactura.PagarRequestBody();
            inValue.Body.facturas = facturas;
            return ((rsFactura.wsNotificadorPagosSoap)(this)).PagarAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsNotificadorPagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsNotificadorPagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsNotificadorPagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55514/wsNotificadorPagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsNotificadorPagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55514/wsNotificadorPagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsNotificadorPagosSoap,
            
            wsNotificadorPagosSoap12,
        }
    }
}
