//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsCotizacion
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rsCotizacion.wsCotizacionSoap")]
    public interface wsCotizacionSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        rsCotizacion.ObtenerCotizacionResponse ObtenerCotizacion(rsCotizacion.ObtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<rsCotizacion.ObtenerCotizacionResponse> ObtenerCotizacionAsync(rsCotizacion.ObtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizacion", ReplyAction="*")]
        rsCotizacion.RegistrarCotizacionResponse RegistrarCotizacion(rsCotizacion.RegistrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<rsCotizacion.RegistrarCotizacionResponse> RegistrarCotizacionAsync(rsCotizacion.RegistrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public rsCotizacion.ObtenerCotizacionRequestBody Body;
        
        public ObtenerCotizacionRequest()
        {
        }
        
        public ObtenerCotizacionRequest(rsCotizacion.ObtenerCotizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public ObtenerCotizacionRequestBody()
        {
        }
        
        public ObtenerCotizacionRequestBody(string fecha)
        {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsCotizacion.ObtenerCotizacionResponseBody Body;
        
        public ObtenerCotizacionResponse()
        {
        }
        
        public ObtenerCotizacionResponse(rsCotizacion.ObtenerCotizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCotizacionResult;
        
        public ObtenerCotizacionResponseBody()
        {
        }
        
        public ObtenerCotizacionResponseBody(string ObtenerCotizacionResult)
        {
            this.ObtenerCotizacionResult = ObtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public rsCotizacion.RegistrarCotizacionRequestBody Body;
        
        public RegistrarCotizacionRequest()
        {
        }
        
        public RegistrarCotizacionRequest(rsCotizacion.RegistrarCotizacionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public RegistrarCotizacionRequestBody()
        {
        }
        
        public RegistrarCotizacionRequestBody(string fecha, decimal monto)
        {
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarCotizacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsCotizacion.RegistrarCotizacionResponseBody Body;
        
        public RegistrarCotizacionResponse()
        {
        }
        
        public RegistrarCotizacionResponse(rsCotizacion.RegistrarCotizacionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarCotizacionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarCotizacionResult;
        
        public RegistrarCotizacionResponseBody()
        {
        }
        
        public RegistrarCotizacionResponseBody(string RegistrarCotizacionResult)
        {
            this.RegistrarCotizacionResult = RegistrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsCotizacionSoapChannel : rsCotizacion.wsCotizacionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsCotizacionSoapClient : System.ServiceModel.ClientBase<rsCotizacion.wsCotizacionSoap>, rsCotizacion.wsCotizacionSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), wsCotizacionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsCotizacionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCotizacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsCotizacion.ObtenerCotizacionResponse rsCotizacion.wsCotizacionSoap.ObtenerCotizacion(rsCotizacion.ObtenerCotizacionRequest request)
        {
            return base.Channel.ObtenerCotizacion(request);
        }
        
        public string ObtenerCotizacion(string fecha)
        {
            rsCotizacion.ObtenerCotizacionRequest inValue = new rsCotizacion.ObtenerCotizacionRequest();
            inValue.Body = new rsCotizacion.ObtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            rsCotizacion.ObtenerCotizacionResponse retVal = ((rsCotizacion.wsCotizacionSoap)(this)).ObtenerCotizacion(inValue);
            return retVal.Body.ObtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsCotizacion.ObtenerCotizacionResponse> rsCotizacion.wsCotizacionSoap.ObtenerCotizacionAsync(rsCotizacion.ObtenerCotizacionRequest request)
        {
            return base.Channel.ObtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsCotizacion.ObtenerCotizacionResponse> ObtenerCotizacionAsync(string fecha)
        {
            rsCotizacion.ObtenerCotizacionRequest inValue = new rsCotizacion.ObtenerCotizacionRequest();
            inValue.Body = new rsCotizacion.ObtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((rsCotizacion.wsCotizacionSoap)(this)).ObtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsCotizacion.RegistrarCotizacionResponse rsCotizacion.wsCotizacionSoap.RegistrarCotizacion(rsCotizacion.RegistrarCotizacionRequest request)
        {
            return base.Channel.RegistrarCotizacion(request);
        }
        
        public string RegistrarCotizacion(string fecha, decimal monto)
        {
            rsCotizacion.RegistrarCotizacionRequest inValue = new rsCotizacion.RegistrarCotizacionRequest();
            inValue.Body = new rsCotizacion.RegistrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            rsCotizacion.RegistrarCotizacionResponse retVal = ((rsCotizacion.wsCotizacionSoap)(this)).RegistrarCotizacion(inValue);
            return retVal.Body.RegistrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsCotizacion.RegistrarCotizacionResponse> rsCotizacion.wsCotizacionSoap.RegistrarCotizacionAsync(rsCotizacion.RegistrarCotizacionRequest request)
        {
            return base.Channel.RegistrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsCotizacion.RegistrarCotizacionResponse> RegistrarCotizacionAsync(string fecha, decimal monto)
        {
            rsCotizacion.RegistrarCotizacionRequest inValue = new rsCotizacion.RegistrarCotizacionRequest();
            inValue.Body = new rsCotizacion.RegistrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            return ((rsCotizacion.wsCotizacionSoap)(this)).RegistrarCotizacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51888/wsCotizacion.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCotizacionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51888/wsCotizacion.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsCotizacionSoap,
            
            wsCotizacionSoap12,
        }
    }
}
