//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rsServidorPagos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://tempuri.org/")]
    public partial class Deuda : object
    {
        
        private string EntidadField;
        
        private string CodigoField;
        
        private string ConceptoField;
        
        private decimal MontoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Entidad
        {
            get
            {
                return this.EntidadField;
            }
            set
            {
                this.EntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Concepto
        {
            get
            {
                return this.ConceptoField;
            }
            set
            {
                this.ConceptoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rsServidorPagos.wsServidorPagosSoap")]
    public interface wsServidorPagosSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verDeuda", ReplyAction="*")]
        rsServidorPagos.verDeudaResponse verDeuda(rsServidorPagos.verDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<rsServidorPagos.verDeudaResponse> verDeudaAsync(rsServidorPagos.verDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento c del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        rsServidorPagos.PagarDeudaResponse PagarDeuda(rsServidorPagos.PagarDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<rsServidorPagos.PagarDeudaResponse> PagarDeudaAsync(rsServidorPagos.PagarDeudaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeuda", Namespace="http://tempuri.org/", Order=0)]
        public rsServidorPagos.verDeudaRequestBody Body;
        
        public verDeudaRequest()
        {
        }
        
        public verDeudaRequest(rsServidorPagos.verDeudaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verDeudaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombres;
        
        public verDeudaRequestBody()
        {
        }
        
        public verDeudaRequestBody(string ci, string PrimerApellido, string SegundoApellido, string nombres)
        {
            this.ci = ci;
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.nombres = nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsServidorPagos.verDeudaResponseBody Body;
        
        public verDeudaResponse()
        {
        }
        
        public verDeudaResponse(rsServidorPagos.verDeudaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verDeudaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsServidorPagos.Deuda[] verDeudaResult;
        
        public verDeudaResponseBody()
        {
        }
        
        public verDeudaResponseBody(rsServidorPagos.Deuda[] verDeudaResult)
        {
            this.verDeudaResult = verDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeuda", Namespace="http://tempuri.org/", Order=0)]
        public rsServidorPagos.PagarDeudaRequestBody Body;
        
        public PagarDeudaRequest()
        {
        }
        
        public PagarDeudaRequest(rsServidorPagos.PagarDeudaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public rsServidorPagos.Deuda c;
        
        public PagarDeudaRequestBody()
        {
        }
        
        public PagarDeudaRequestBody(rsServidorPagos.Deuda c)
        {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public rsServidorPagos.PagarDeudaResponseBody Body;
        
        public PagarDeudaResponse()
        {
        }
        
        public PagarDeudaResponse(rsServidorPagos.PagarDeudaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PagarDeudaResult;
        
        public PagarDeudaResponseBody()
        {
        }
        
        public PagarDeudaResponseBody(bool PagarDeudaResult)
        {
            this.PagarDeudaResult = PagarDeudaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsServidorPagosSoapChannel : rsServidorPagos.wsServidorPagosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsServidorPagosSoapClient : System.ServiceModel.ClientBase<rsServidorPagos.wsServidorPagosSoap>, rsServidorPagos.wsServidorPagosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsServidorPagosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsServidorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsServidorPagosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsServidorPagosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsServidorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsServidorPagosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsServidorPagosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsServidorPagosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsServidorPagos.verDeudaResponse rsServidorPagos.wsServidorPagosSoap.verDeuda(rsServidorPagos.verDeudaRequest request)
        {
            return base.Channel.verDeuda(request);
        }
        
        public rsServidorPagos.Deuda[] verDeuda(string ci, string PrimerApellido, string SegundoApellido, string nombres)
        {
            rsServidorPagos.verDeudaRequest inValue = new rsServidorPagos.verDeudaRequest();
            inValue.Body = new rsServidorPagos.verDeudaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.nombres = nombres;
            rsServidorPagos.verDeudaResponse retVal = ((rsServidorPagos.wsServidorPagosSoap)(this)).verDeuda(inValue);
            return retVal.Body.verDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsServidorPagos.verDeudaResponse> rsServidorPagos.wsServidorPagosSoap.verDeudaAsync(rsServidorPagos.verDeudaRequest request)
        {
            return base.Channel.verDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsServidorPagos.verDeudaResponse> verDeudaAsync(string ci, string PrimerApellido, string SegundoApellido, string nombres)
        {
            rsServidorPagos.verDeudaRequest inValue = new rsServidorPagos.verDeudaRequest();
            inValue.Body = new rsServidorPagos.verDeudaRequestBody();
            inValue.Body.ci = ci;
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.nombres = nombres;
            return ((rsServidorPagos.wsServidorPagosSoap)(this)).verDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        rsServidorPagos.PagarDeudaResponse rsServidorPagos.wsServidorPagosSoap.PagarDeuda(rsServidorPagos.PagarDeudaRequest request)
        {
            return base.Channel.PagarDeuda(request);
        }
        
        public bool PagarDeuda(rsServidorPagos.Deuda c)
        {
            rsServidorPagos.PagarDeudaRequest inValue = new rsServidorPagos.PagarDeudaRequest();
            inValue.Body = new rsServidorPagos.PagarDeudaRequestBody();
            inValue.Body.c = c;
            rsServidorPagos.PagarDeudaResponse retVal = ((rsServidorPagos.wsServidorPagosSoap)(this)).PagarDeuda(inValue);
            return retVal.Body.PagarDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<rsServidorPagos.PagarDeudaResponse> rsServidorPagos.wsServidorPagosSoap.PagarDeudaAsync(rsServidorPagos.PagarDeudaRequest request)
        {
            return base.Channel.PagarDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<rsServidorPagos.PagarDeudaResponse> PagarDeudaAsync(rsServidorPagos.Deuda c)
        {
            rsServidorPagos.PagarDeudaRequest inValue = new rsServidorPagos.PagarDeudaRequest();
            inValue.Body = new rsServidorPagos.PagarDeudaRequestBody();
            inValue.Body.c = c;
            return ((rsServidorPagos.wsServidorPagosSoap)(this)).PagarDeudaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsServidorPagosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsServidorPagosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsServidorPagosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61171/wsServidorPagos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsServidorPagosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61171/wsServidorPagos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsServidorPagosSoap,
            
            wsServidorPagosSoap12,
        }
    }
}
